name: Docker Image CI

on:
  push:
    tags:
      - v*
env:
  APP_NAME: web-search
  DOCKERHUB_REPO: sadlay/web-search
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0
    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Generate App Version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV    
    - name: Build and Push
      uses: docker/build-push-action@v5.3.0
      with:
        platforms: |
            linux/amd64
            linux/arm64
        push: true
        build-args: |
          APP_NAME=${{ env.APP_NAME }}
          APP_VERSION=${{ env.APP_VERSION }}
        tags: |
          ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
          ${{ env.DOCKERHUB_REPO }}:latest
          
